spring:
  application:
    name: microservice-rabbitMQ #在eureka里显示的application的名字
  profiles:
    active: dev
server:
  port: 5777
  

  
#不在eureka里注册
#eureka:
#  client:
#    register-with-eureka: false